napvig:
  topics:
    subs:
      measures: /turtlebot/scan
      odom: /turtlebot/odom
      target: /target/pose
      external_clock: /external_clock
      unset_target: /target/unset
    pubs:
      command: /cmd_pose
      command_world: /cmd_pose_world
    output_prefix: /napvig/outputs
    outputs:
      - measures
      - pose_debug
      - values
      - gradients
      - history
      - target_in_measures
      - string

unicycle_control:
  topics:
    reference_sub: /cmd_pose
    cmd_vel_pub: /turtlebot/cmd_vel

target:                                   # shouldn't be here, but... 
  rate: 10                            
  target_pub: /target/pose